/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ilfucileresto.vistas;

import ilfucileresto.AccesoADatos.ProductoData;
import ilfucileresto.Entidades.Producto;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrubio
 */
public class Productos extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    private ProductoData pD = new ProductoData();

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        cargarColumna();
        mostrarDatosTabla();
        txtNombreProducto.setEnabled(false);
        txtPrecioUnitario.setEnabled(false);
        txtStock.setEnabled(false);
        rbEstado.setEnabled(false);
        if (Menu.usuario.equals("MESERO")) {
            btnAgregarProducto.setEnabled(false);
            btnEliminarProducto.setEnabled(false);
            btnModificarProducto.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCargaDatos = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        rbEstado = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1145, 690));

        pnCargaDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilfucileresto/Imagenes/agregar-producto.png"))); // NOI18N
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilfucileresto/Imagenes/editar-codigo.png"))); // NOI18N
        btnModificarProducto.setText("Modificar");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilfucileresto/Imagenes/eliminar-producto.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        txtPrecioUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioUnitarioKeyTyped(evt);
            }
        });

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        rbEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEstadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Precio Unit.:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Stock:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCargaDatosLayout = new javax.swing.GroupLayout(pnCargaDatos);
        pnCargaDatos.setLayout(pnCargaDatosLayout);
        pnCargaDatosLayout.setHorizontalGroup(
            pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargaDatosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCargaDatosLayout.createSequentialGroup()
                        .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargaDatosLayout.createSequentialGroup()
                                .addComponent(rbEstado)
                                .addGap(229, 229, 229))))
                    .addGroup(pnCargaDatosLayout.createSequentialGroup()
                        .addComponent(btnAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarProducto)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargaDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(62, 62, 62))
        );
        pnCargaDatosLayout.setVerticalGroup(
            pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargaDatosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnModificarProducto)
                    .addComponent(btnEliminarProducto))
                .addGap(41, 41, 41)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(rbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(pnCargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(31, 31, 31))
        );

        jPanel3.setBackground(new java.awt.Color(102, 32, 6));
        jPanel3.setPreferredSize(new java.awt.Dimension(659, 74));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menú");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbMenu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Administración de Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pnCargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(134, 134, 134))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(pnCargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 110, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAgregarProducto() {
        return btnAgregarProducto;
    }

    public void setBtnAgregarProducto(JButton btnAgregarProducto) {
        this.btnAgregarProducto = btnAgregarProducto;
    }

    public JButton getBtnEliminarProducto() {
        return btnEliminarProducto;
    }

    public void setBtnEliminarProducto(JButton btnEliminarProducto) {
        this.btnEliminarProducto = btnEliminarProducto;
    }

    public JButton getBtnModificarProducto() {
        return btnModificarProducto;
    }

    public void setBtnModificarProducto(JButton btnModificarProducto) {
        this.btnModificarProducto = btnModificarProducto;
    }

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed

        txtNombreProducto.setText("");
        txtPrecioUnitario.setText("");
        txtStock.setText("");
        btnModificarProducto.setEnabled(false);
        btnEliminarProducto.setEnabled(false);
        btnAceptar.setEnabled(true);
        btnCancelar.setEnabled(true);
        rbEstado.setSelected(true);
        rbEstado.setEnabled(false);
        txtNombreProducto.setEnabled(true);
        txtPrecioUnitario.setEnabled(true);
        txtStock.setEnabled(true);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (btnAgregarProducto.isEnabled()) {
            int stock = Integer.parseInt(txtStock.getText());
            if (txtNombreProducto.getText().isEmpty() || txtPrecioUnitario.getText().isEmpty()
                    || txtStock.getText().isEmpty() || stock < 1) {
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
                return;
            }
            Producto producto = new Producto();
            try {
                producto.setNombreProducto(txtNombreProducto.getText());
                producto.setPrecioUnitario(Double.valueOf(txtPrecioUnitario.getText()));
                producto.setStock(stock);
                producto.setEstado(true);
                pD.guardarProducto(producto);
                txtNombreProducto.setText("");
                txtPrecioUnitario.setText("");
                txtStock.setText("");
                rbEstado.setSelected(false);
                mostrarDatosTabla();
            } catch (NumberFormatException nf) {
                JOptionPane.showMessageDialog(this, "Ingrese un Precio válido.");
                txtPrecioUnitario.setText("");
                txtPrecioUnitario.setFocusable(true);
                return;
            }

        } else if (btnModificarProducto.isEnabled()) {
            if (txtNombreProducto.getText().isEmpty() || txtPrecioUnitario.getText().isEmpty() || txtStock.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
                return;
            }
            Producto producto = new Producto();
            try {
                producto.setIdProducto((Integer) modelo.getValueAt(tbMenu.getSelectedRow(), 0));
                producto.setNombreProducto(txtNombreProducto.getText());
                producto.setPrecioUnitario(Double.valueOf(txtPrecioUnitario.getText()));
                producto.setStock(Integer.valueOf(txtStock.getText()));
                producto.setEstado(rbEstado.isSelected());
                pD.modificarProducto(producto);
                txtNombreProducto.setText("");
                txtPrecioUnitario.setText("");
                txtStock.setText("");
                rbEstado.setSelected(false);
                mostrarDatosTabla();
            } catch (NumberFormatException nf) {
                JOptionPane.showMessageDialog(this, "Ingrese un Precio válido.");
                txtPrecioUnitario.setText("");
                txtPrecioUnitario.setFocusable(true);
                return;
            }

        } else if (btnEliminarProducto.isEnabled()) {
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el producto?", "Eliminar Producto", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                Producto producto = new Producto();
                producto.setIdProducto((Integer) modelo.getValueAt(tbMenu.getSelectedRow(), 0));
                producto.setNombreProducto(txtNombreProducto.getText());
                producto.setPrecioUnitario(Double.valueOf(txtPrecioUnitario.getText()));
                producto.setStock(Integer.valueOf(txtStock.getText()));
                producto.setEstado(false);
                pD.modificarProducto(producto);
                txtNombreProducto.setText("");
                txtPrecioUnitario.setText("");
                txtStock.setText("");
                rbEstado.setSelected(false);
                mostrarDatosTabla();
            }
        }

        btnEliminarProducto.setEnabled(true);
        btnAgregarProducto.setEnabled(true);
        btnModificarProducto.setEnabled(true);
        btnAceptar.setEnabled(false);
        btnCancelar.setEnabled(false);
        deshabilitarTexts();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed

        if (tbMenu.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }
        btnAceptar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAgregarProducto.setEnabled(false);
        btnEliminarProducto.setEnabled(false);
        rbEstado.setSelected(true);
        rbEstado.setEnabled(false);
        Integer id = (Integer) modelo.getValueAt(tbMenu.getSelectedRow(), 0);
        Producto producto = pD.buscarProducto(id);
        txtNombreProducto.setText(producto.getNombreProducto());
        txtPrecioUnitario.setText(producto.getPrecioUnitario() + "");
        txtStock.setText(producto.getStock() + "");
        txtNombreProducto.setEnabled(true);
        txtPrecioUnitario.setEnabled(true);
        txtStock.setEnabled(true);
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        btnModificarProducto.setEnabled(true);
        btnEliminarProducto.setEnabled(true);
        btnAgregarProducto.setEnabled(true);
        txtNombreProducto.setText("");
        txtPrecioUnitario.setText("");
        txtStock.setText("");
        btnAceptar.setEnabled(false);
        btnCancelar.setEnabled(false);
        deshabilitarTexts();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        if (tbMenu.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }
        txtNombreProducto.setEnabled(false);
        txtPrecioUnitario.setEnabled(false);
        txtStock.setEnabled(false);
        rbEstado.setEnabled(false);
        btnAceptar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAgregarProducto.setEnabled(false);
        btnModificarProducto.setEnabled(false);
        Integer id = (Integer) modelo.getValueAt(tbMenu.getSelectedRow(), 0);
        Producto producto = pD.buscarProducto(id);
        txtNombreProducto.setText(producto.getNombreProducto());
        txtPrecioUnitario.setText(producto.getPrecioUnitario() + "");
        txtStock.setText(producto.getStock() + "");


    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void rbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEstadoActionPerformed

    private void tbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMouseClicked
        if (tbMenu.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }

        if (btnAgregarProducto.isEnabled() && !btnModificarProducto.isEnabled()) {
            return;
        }

        Integer id = (Integer) modelo.getValueAt(tbMenu.getSelectedRow(), 0);
        Producto producto = pD.buscarProducto(id);
        txtNombreProducto.setText(producto.getNombreProducto());
        txtPrecioUnitario.setText(producto.getPrecioUnitario() + "");
        txtStock.setText(producto.getStock() + "");


    }//GEN-LAST:event_tbMenuMouseClicked

    private void txtPrecioUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioKeyTyped
        char caracter = evt.getKeyChar();
        if (!(((caracter >= '0') && (caracter <= '9') || (caracter == '.') || (caracter == KeyEvent.VK_DELETE)))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioUnitarioKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char caracter = evt.getKeyChar();
        if (!(((caracter >= '0') && (caracter <= '9') || (caracter == KeyEvent.VK_DELETE)))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtStockKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnCargaDatos;
    private javax.swing.JRadioButton rbEstado;
    private javax.swing.JTable tbMenu;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    public void cargarColumna() {

        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("PrecioUnitario");
        modelo.addColumn("Stock");
        modelo.addColumn("Estado");

        tbMenu.setModel(modelo);

    }

    private void mostrarDatosTabla() {
        String estado;
        List<Producto> productos = pD.listarProductos();
        modelo.setRowCount(0);
        for (Producto producto : productos) {
            if (producto.isEstado()) {
                estado = "Disponible";
            } else {
                estado = "No Disponible";
            }

            modelo.addRow(new Object[]{producto.getIdProducto(), producto.getNombreProducto(), producto.getPrecioUnitario(), producto.getStock(), estado});

        }

    }

    private void deshabilitarTexts() {
        txtNombreProducto.setEnabled(false);
        txtPrecioUnitario.setEnabled(false);
        txtStock.setEnabled(false);
    }

    private void habilitarTexts() {
        txtNombreProducto.setEnabled(true);
        txtPrecioUnitario.setEnabled(true);
        txtStock.setEnabled(true);
    }

    public void deshabilitarPanel() {
        btnAgregarProducto.setEnabled(false);
        btnEliminarProducto.setEnabled(false);
        btnModificarProducto.setEnabled(false);
    }

}
